[package]
name = "feos-campd"
version = "0.1.0"
edition = "2021"

[lib]
name = "feos_campd"
crate-type = ["rlib", "cdylib"]

[dependencies]
quantity = "0.5"
feos-core = "0.2"
ndarray = "0.15"
petgraph = "0.6"
feos-pcsaft = { path = "../feos-pcsaft" }
feos-gc-pcsaft = { path = "../feos-gc-pcsaft" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
numpy = { version = "0.16", optional = true }

[dependencies.pyo3]
version = "0.16"
features = ["extension-module", "abi3", "abi3-py37"]
optional = true

[dev-dependencies]
itertools = "0.10"
approx = "0.5"

[features]
default = ["python"]
python = ["pyo3", "numpy", "feos-core/python"]