[package]
name = "feos-campd"
version = "0.1.0"
edition = "2021"

[dependencies]
quantity = "0.5"
feos-core = { git = "https://github.com/feos-org/feos" }
feos = { git = "https://github.com/feos-org/feos", features = ["pcsaft", "gc_pcsaft"] }
ndarray = "0.15"
petgraph = "0.6"
serde = "1.0"
serde_json = "1.0"
rayon = { version = "1.5", optional = true }
knitro_rs = { path = "knitro_rs", optional = true }

[dev-dependencies]
itertools = "0.10"
approx = "0.5"

[features]
default = []
knitro_12 = ["knitro_rs/knitro_12", "rayon"]
knitro_13 = ["knitro_rs/knitro_13", "rayon"]