[package]
name = "feos-campd"
version = "0.3.3"
authors = ["Philipp Rehner <prehner@ethz.ch>"]
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Computer-aided molecular and process design using the FeOs framework."
homepage = "https://github.com/feos-org"
repository = "https://github.com/feos-org/feos-campd"
keywords = ["process_engineering", "molecular_design", "optimization"]
categories = ["science"]

[dependencies]
num-dual = "0.13"
quantity = "0.12"
nalgebra = "0.34"
feos = { version = "0.9", features = ["pcsaft", "gc_pcsaft"] }
num-traits = "0.2"
good_lp = { version = "1", default-features = false }
#ipopt = "0.6"
ipopt = { git = "https://github.com/prehner/ipopt-rs", branch = "static_linking" }
ipopt-ad = { git = "https://github.com/prehner/ipopt-ad" }
serde = "1"

[dev-dependencies]
approx = "0.5"
quantity = { version = "0.12", features = ["approx"] }
itertools = "0.14"

[features]
default = ["highs"]
highs = ["good_lp/highs"]
