[package]
name = "feos-campd"
version = "0.1.0"
edition = "2018"

[lib]
name = "feos_campd"
crate-type = ["rlib", "cdylib"]

[dependencies]
quantity = "0.4"
feos-core = "0.1"
ndarray = "0.15"
petgraph = "0.6"
num-traits = "0.2"
num-dual = "0.4"
feos-pcsaft = { path = "../feos-pcsaft" }
feos-gc-pcsaft = { path = "../feos-gc-pcsaft" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
numpy = { version = "0.15", optional = true }

[dependencies.pyo3]
version = "0.15"
features = ["extension-module", "abi3", "abi3-py36"]
optional = true

[dev-dependencies]
itertools = "0.10"

[features]
default = []
python = ["pyo3", "numpy", "feos-core/python"]