[package]
name = "feos-campd"
version = "0.1.0"
edition = "2021"

[dependencies]
quantity = "0.5"
feos-core = { path = "../feos-core" }
ndarray = "0.15"
petgraph = "0.6"
serde = "1.0"
serde_json = "1.0"
rayon = { version = "1.5", optional = true }
knitro_rs = { path = "knitro_rs", optional = true }

[dev-dependencies]
feos-pcsaft = { path = "../feos-pcsaft", features = ["campd"] }
itertools = "0.10"
approx = "0.5"

[features]
default = []
knitro_12 = ["knitro_rs/knitro_12", "rayon"]
knitro_13 = ["knitro_rs/knitro_13", "rayon"]