name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release-crates-io-knitro_rs:
    name: Release knitro-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          args: --features knitro_12
          path: './knitro_rs'

  release-crates-io:
    name: Release feos-campd
    runs-on: ubuntu-latest
    needs: [release-crates-io-knitro_rs]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}